### ISSUE TITLE
Tablist Nickname

### ISSUE THREAD

**Issue by HiperBulu** [InventivetalentDev/Murder#2]
## What steps will reproduce the problem?  
1. On start game 

## What were you expecting to happen? What happened instead?  
When a player join into the game, a Times 
![image](https://cloud.githubusercontent.com/assets/18380470/15808132/ed40f324-2b6f-11e6-97f7-6855c4ceeec5.jpg)
the nickname don't change in the tablist and in game i need to type refreshnick and axe don't shoot
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.1.2
## What Spigot versione are you using? *Type /version*  
1.9
## What plugins ae you using? *Type /plugins*  
[15:06:51 INFO]: Plugins (18): ResourcePackApi, WorldEdit, Skript, Essentials, EssentialsChat, BossBarAPI, PacketListenerApi, PermissionsEx, ItemBuilder, ParticleLIB, EssentialsSpawn, PlayerVersion, TitleAPI, NickNamer, MenuBuilder, EntityAnimationAPI, NPCLib, Murder

**Comment by HiperBulu** [comment]
Prominkanizza don't Changed Name bug joined in the Murder minigame

**Comment by GabbiGalber** [comment]
Yeah! I've this bug too!

**Comment by HiperBulu** [comment]
Wait a reponse from inventivatalent

**Comment by HiperBulu** [comment]
And skin don't change

**Comment by InventivetalentDev** [comment]
Is 'Prominkanizza' your own name? Does it change for other players?
If it works after refreshing the name, this should probably be simple to fix.  

Please create a separate issue for the axe-throwing problems.

**Comment by HiperBulu** [comment]
Yes promikkanizza is my name, but this dont change when i join in murder

**Comment by InventivetalentDev** [comment]
But does it change for other players?

**Comment by HiperBulu** [comment]
Sometimes changes and sometimes not

**Comment by HiperBulu** [comment]
I tested with antoher account and the name still don't change

**Comment by HiperBulu** [comment]
Solved with a custom plugin

**Comment by InventivetalentDev** [comment]
Feel free to share the solution / create a pull request :)
