### ISSUE TITLE
Murder_v3.3.1-SNAPSHOT Not working on 1.11.2

### ISSUE THREAD

**Issue by Dinodudeishgamer** [InventivetalentDev/Murder#32]
## What steps will reproduce the problem?  
1. 
2. 
3. 

## What were you expecting to happen? What happened instead?  
It to work, it doesn't. I can't even type in commands for the plugin. Plugin name shows up red when I do /plugins
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
latest
## What Spigot version are you using? *Type /version*  
latest
## What plugins are you using? *Type /plugins*  
25 plugins.... don't wanna list them all :/
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
nope
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope

**Comment by InventivetalentDev** [comment]
Provide more information, or there's no way I can properly help you.
